
// fetch roles
export const FETCH_ROLES_REQUEST = 'FETCH_ROLES_REQUEST';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_FAILURE = 'FETCH_ROLES_FAILURE';
// fetch role
export const FETCH_ROLE_REQUEST = 'FETCH_ROLE_REQUEST';
export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS';
export const FETCH_ROLE_FAILURE = 'FETCH_ROLE_FAILURE';
// create roles
export const CREATE_ROLES_REQUEST = 'CREATE_ROLES_REQUEST';
export const CREATE_ROLES_SUCCESS = 'CREATE_ROLES_SUCCESS';
export const CREATE_ROLES_FAILURE = 'CREATE_ROLES_FAILURE';
// update role
export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAILURE = 'UPDATE_ROLE_FAILURE';
// role allocation
export const ROLE_PERMISSION_ALLOC_REQUEST = 'ROLE_PERMISSION_ALLOC_REQUEST';
export const ROLE_PERMISSION_ALLOC_SUCCESS = 'ROLE_PERMISSION_ALLOC_SUCCESS';
export const ROLE_PERMISSION_ALLOC_FAILURE = 'ROLE_PERMISSION_ALLOC_FAILURE';
// role de-allocation
export const ROLE_PERMISSION_DEALLOC_REQUEST = 'ROLE_PERMISSION_DEALLOC_REQUEST';
export const ROLE_PERMISSION_DEALLOC_SUCCESS = 'ROLE_PERMISSION_DEALLOC_SUCCESS';
export const ROLE_PERMISSION_DEALLOC_FAILURE = 'ROLE_PERMISSION_DEALLOC_FAILURE';
// delete roles
export const DELETE_ROLES_REQUEST = 'DELETE_ROLES_REQUEST';
export const DELETE_ROLES_SUCCESS = 'DELETE_ROLES_SUCCESS';
export const DELETE_ROLES_FAILURE = 'DELETE_ROLES_FAILURE';
