
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_MY_PROFILE_REQUEST = 'FETCH_MY_PROFILE_REQUEST';
export const FETCH_MY_PROFILE_SUCCESS = 'FETCH_MY_PROFILE_SUCCESS';
export const FETCH_MY_PROFILE_FAILURE = 'FETCH_MY_PROFILE_FAILURE';

export const FETCH_OTHER_ROFILE_REQUEST = 'FETCH_OTHER_ROFILE_REQUEST';
export const FETCH_OTHER_ROFILE_SUCCESS = 'FETCH_OTHER_ROFILE_SUCCESS';
export const FETCH_OTHER_ROFILE_FAILURE = 'FETCH_OTHER_ROFILE_FAILURE';

export const CREATE_USERS_REQUEST = 'CREATE_USERS_REQUEST';
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';
export const CREATE_USERS_FAILURE = 'CREATE_USERS_FAILURE';

export const UPDATE_LOGINS_REQUEST = 'UPDATE_LOGINS_REQUEST';
export const UPDATE_LOGINS_SUCCESS = 'UPDATE_LOGINS_SUCCESS';
export const UPDATE_LOGINS_FAILURE = 'UPDATE_LOGINS_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const ENROLL_STAFF_REQUEST = 'ENROLL_STAFF_REQUEST';
export const ENROLL_STAFF_SUCCESS = 'ENROLL_STAFF_SUCCESS';
export const ENROLL_STAFF_FAILURE = 'ENROLL_STAFF_FAILURE';
