
export const FETCH_SUBSCRIPTIONS_REQUEST = 'FETCH_SUBSCRIPTIONS_REQUEST';
export const FETCH_SUBSCRIPTIONS_SUCCESS = 'FETCH_SUBSCRIPTIONS_SUCCESS';
export const FETCH_SUBSCRIPTIONS_FAILURE = 'FETCH_SUBSCRIPTIONS_FAILURE';

export const FETCH_SUBSCRIPTION_REQUEST = 'FETCH_SUBSCRIPTION_REQUEST';
export const FETCH_SUBSCRIPTION_SUCCESS = 'FETCH_SUBSCRIPTION_SUCCESS';
export const FETCH_SUBSCRIPTION_FAILURE = 'FETCH_SUBSCRIPTION_FAILURE';

export const DELETE_SUBSCRIPTION_REQUEST = 'DELETE_SUBSCRIPTION_REQUEST';
export const DELETE_SUBSCRIPTION_SUCCESS = 'DELETE_SUBSCRIPTION_SUCCESS';
export const DELETE_SUBSCRIPTION_FAILURE = 'DELETE_SUBSCRIPTION_FAILURE';

export const CREATE_FAQ_REQUEST = 'CREATE_FAQ_REQUEST';
export const CREATE_FAQ_SUCCESS = 'CREATE_FAQ_SUCCESS';
export const CREATE_FAQ_FAILURE = 'CREATE_FAQ_FAILURE';

export const UPDATE_FAQ_REQUEST = 'UPDATE_FAQ_REQUEST';
export const UPDATE_FAQ_SUCCESS = 'UPDATE_FAQ_SUCCESS';
export const UPDATE_FAQ_FAILURE = 'UPDATE_FAQ_FAILURE';

export const DELETE_FAQS_REQUEST = 'DELETE_FAQS_REQUEST';
export const DELETE_FAQS_SUCCESS = 'DELETE_FAQS_SUCCESS';
export const DELETE_FAQS_FAILURE = 'DELETE_FAQS_FAILURE';

export const FETCH_FAQ_REQUEST = 'FETCH_FAQ_REQUEST';
export const FETCH_FAQ_SUCCESS = 'FETCH_FAQ_SUCCESS';
export const FETCH_FAQ_FAILURE = 'FETCH_FAQ_FAILURE';

export const FETCH_FAQS_REQUEST = 'FETCH_FAQS_REQUEST';
export const FETCH_FAQS_SUCCESS = 'FETCH_FAQS_SUCCESS';
export const FETCH_FAQS_FAILURE = 'FETCH_FAQS_FAILURE';

export const CREATE_FAQCAT_REQUEST = 'CREATE_FAQCAT_REQUEST';
export const CREATE_FAQCAT_SUCCESS = 'CREATE_FAQCAT_SUCCESS';
export const CREATE_FAQCAT_FAILURE = 'CREATE_FAQCAT_FAILURE';

export const UPDATE_FAQCAT_REQUEST = 'UPDATE_FAQCAT_REQUEST';
export const UPDATE_FAQCAT_SUCCESS = 'UPDATE_FAQCAT_SUCCESS';
export const UPDATE_FAQCAT_FAILURE = 'UPDATE_FAQCAT_FAILURE';

export const DELETE_FAQCATS_REQUEST = 'DELETE_FAQCATS_REQUEST';
export const DELETE_FAQCATS_SUCCESS = 'DELETE_FAQCATS_SUCCESS';
export const DELETE_FAQCATS_FAILURE = 'DELETE_FAQCATS_FAILURE';

export const FETCH_FAQCAT_REQUEST = 'FETCH_FAQCAT_REQUEST';
export const FETCH_FAQCAT_SUCCESS = 'FETCH_FAQCAT_SUCCESS';
export const FETCH_FAQCAT_FAILURE = 'FETCH_FAQCAT_FAILURE';

export const FETCH_FAQCATS_REQUEST = 'FETCH_FAQCATS_REQUEST';
export const FETCH_FAQCATS_SUCCESS = 'FETCH_FAQCATS_SUCCESS';
export const FETCH_FAQCATS_FAILURE = 'FETCH_FAQCATS_FAILURE';
