
export const FETCH_GOODS_CATEGORY_REQUEST = 'FETCH_GOODS_CATEGORY_REQUEST';
export const FETCH_GOODS_CATEGORY_SUCCESS = 'FETCH_GOODS_CATEGORY_SUCCESS';
export const FETCH_GOODS_CATEGORY_FAILURE = 'FETCH_GOODS_CATEGORY_FAILURE';

export const FETCH_GOODS_CATEGORIES_REQUEST = 'FETCH_GOODS_CATEGORIES_REQUEST';
export const FETCH_GOODS_CATEGORIES_SUCCESS = 'FETCH_GOODS_CATEGORIES_SUCCESS';
export const FETCH_GOODS_CATEGORIES_FAILURE = 'FETCH_GOODS_CATEGORIES_FAILURE';

export const FETCH_GOODS_SUB_CATEGORY_REQUEST = 'FETCH_GOODS_SUB_CATEGORY_REQUEST';
export const FETCH_GOODS_SUB_CATEGORY_SUCCESS = 'FETCH_GOODS_SUB_CATEGORY_SUCCESS';
export const FETCH_GOODS_SUB_CATEGORY_FAILURE = 'FETCH_GOODS_SUB_CATEGORY_FAILURE';

export const FETCH_GOODS_SUB_CATEGORIES_REQUEST = 'FETCH_GOODS_SUB_CATEGORIES_REQUEST';
export const FETCH_GOODS_SUB_CATEGORIES_SUCCESS = 'FETCH_GOODS_SUB_CATEGORIES_SUCCESS';
export const FETCH_GOODS_SUB_CATEGORIES_FAILURE = 'FETCH_GOODS_SUB_CATEGORIES_FAILURE';

export const SAVE_BOOKING_REQUEST = 'SAVE_BOOKING_REQUEST';
export const SAVE_BOOKING_SUCCESS = 'SAVE_BOOKING_SUCCESS';
export const SAVE_BOOKING_FAILURE = 'SAVE_BOOKING_FAILURE';

export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';

export const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FAILURE = 'SEND_ORDER_FAILURE';

export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

export const TRACK_ORDER_REQUEST = 'TRACK_ORDER_REQUEST';
export const TRACK_ORDER_SUCCESS = 'TRACK_ORDER_SUCCESS';
export const TRACK_ORDER_FAILURE = 'TRACK_ORDER_FAILURE';
