
export const FETCH_ORGANIZATION_REQUEST = 'FETCH_ORGANIZATION_REQUEST';
export const FETCH_ORGANIZATION_SUCCESS = 'FETCH_ORGANIZATION_SUCCESS';
export const FETCH_ORGANIZATION_FAILURE = 'FETCH_ORGANIZATION_FAILURE';

export const SEND_CONTACT_MESSAGE_REQUEST = 'SEND_CONTACT_MESSAGE_REQUEST';
export const SEND_CONTACT_MESSAGE_SUCCESS = 'SEND_CONTACT_MESSAGE_SUCCESS';
export const SEND_CONTACT_MESSAGE_FAILURE = 'SEND_CONTACT_MESSAGE_FAILURE';

export const SEND_SUBSCRIPTION_REQUEST = 'SEND_SUBSCRIPTION_REQUEST';
export const SEND_SUBSCRIPTION_SUCCESS = 'SEND_SUBSCRIPTION_SUCCESS';
export const SEND_SUBSCRIPTION_FAILURE = 'SEND_SUBSCRIPTION_FAILURE';

export const FETCH_FAQCATS_REQUEST = 'FETCH_FAQCATS_REQUEST';
export const FETCH_FAQCATS_SUCCESS = 'FETCH_FAQCATS_SUCCESS';
export const FETCH_FAQCATS_FAILURE = 'FETCH_FAQCATS_FAILURE';

export const FETCH_TEAM_REQUEST = 'FETCH_TEAM_REQUEST';
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS';
export const FETCH_TEAM_FAILURE = 'FETCH_TEAM_FAILURE';
